# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'WebViewRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WebViewRxSwift
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxOptional'

end
